### ISSUE TITLE
Application version 8 Crashing when switching in/out of app

### ISSUE THREAD

**Issue by pigottlaura** [wishiwashere/TeamProject-2016#3]
Application 8 on the Play Store (Sprint-003-Alpha-08) appears to be crashing if the user switches between apps in quick succession. The error reported on Google Play is as follows : 

        java.lang.RuntimeException: Method called after release()
	at android.hardware.Camera.setHasPreviewCallback(Native Method)
	at android.hardware.Camera.access$600(Camera.java:150)
	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1158)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

We feel this may be to do with the ketaiCamera continually trying to run in the background, as this "Method called after release()" error is something we have seen previously when trying to call savePhoto() on the camera after it has been stopped.

**Comment by pigottlaura** [comment]
This has now been resolved, as the Ketai camera is now stopped when a user leaves the app. Note - crashes can still occur when opening/closing the app repeatedly, but this is due to out of memory issues (which is logged as a seperate [issue](https://github.com/wishiwashere/TeamProject-2016/issues/7))
